version: '3.8'

services:
  mongo-db-client:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: fiap-lanches-client
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-client:/data/db
    networks:
      - fiap-lanchonet-network

  fiap-lanches-client-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: fiap-lanches-client-api
    ports:
      - "8085:8085"
    volumes:
      - fiap-lanches-client-api:/var/lib/fiaplancher/data
    depends_on:
      - mongo-db-client
    networks:
      - fiap-lanchonet-network

networks:
  fiap-lanchonet-network:
    external: true

volumes:
  mongo-db-client:
    driver: local
  fiap-lanches-client-api:
    driver: local
