version: '3.8'

services:
  postgres-db-conta:
    image: postgres
    hostname: postgres-db-conta
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-client
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-conta:/var/lib/postgresql/data
    networks:
      - fiap-lanchonet-network
  
  fiap-lanches-client-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: fiap-lanches-client-api
    ports:
      - "8085:8085"
    volumes:
      - fiap-lanches-client-api:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db-conta
    networks:
      - fiap-lanchonet-network

networks:
  fiap-lanchonet-network:
    external: true

volumes:
  postgres-db-conta:
    driver: local
  fiap-lanches-client-api:
    driver: local
