spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fiap-lanches-client}
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8085

logging:
  level:
    root: error
    org.springframework: error

app:
  db:
    init:
      enabled: true